version: "3.9"

services:
  db:
    image: postgres:15
    container_name: etl_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: etl_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/etl_db
      PORT: 3000
    ports:
      - "3000:3000"
    restart: always

volumes:
  pg_data:
